BEGIN TRANSACTION;
CREATE TABLE _lang (ID INTEGER PRIMARY KEY, code3 TEXT, code2 TEXT, description TEXT, icon TEXT);
INSERT INTO _lang VALUES(1,'aar','aa','Afar','');
INSERT INTO _lang VALUES(2,'ach','','Acoli','');
INSERT INTO _lang VALUES(3,'ada','','Adangme','');
INSERT INTO _lang VALUES(4,'ady','','Adyghe; Adygei','');
INSERT INTO _lang VALUES(5,'abk','ab','Abkhaz','');
INSERT INTO _lang VALUES(6,'ace','','Acehnese; Achinese','');
INSERT INTO _lang VALUES(7,'afh','','Afrihili','');
INSERT INTO _lang VALUES(8,'afr','af','Afrikaans','');
INSERT INTO _lang VALUES(9,'afa','','Afro-Asiatic (Other)','');
INSERT INTO _lang VALUES(10,'ain','','Ainu','');
INSERT INTO _lang VALUES(11,'aka','ak','Akan','');
INSERT INTO _lang VALUES(12,'akk','','Akkadian','');
INSERT INTO _lang VALUES(13,'sqi','sq','Albanian','');
INSERT INTO _lang VALUES(14,'alb','sq','Albanian','');
INSERT INTO _lang VALUES(15,'ale','','Aleut','');
INSERT INTO _lang VALUES(16,'alg','','Algonquian languages','');
INSERT INTO _lang VALUES(17,'tut','','Altaic (Other)','');
INSERT INTO _lang VALUES(18,'amh','am','Amharic','');
INSERT INTO _lang VALUES(19,'anp','','Angika','');
INSERT INTO _lang VALUES(20,'apa','','Apache languages','');
INSERT INTO _lang VALUES(21,'ara','ar','Arabic','');
INSERT INTO _lang VALUES(22,'arg','an','Aragonese','');
INSERT INTO _lang VALUES(23,'arc','','Aramaic','');
INSERT INTO _lang VALUES(24,'arp','','Arapaho','');
INSERT INTO _lang VALUES(25,'arn','','Araucanian','');
INSERT INTO _lang VALUES(26,'arw','','Arawak','');
INSERT INTO _lang VALUES(27,'hye','hy','Armenian','');
INSERT INTO _lang VALUES(28,'arm','hy','Armenian','');
INSERT INTO _lang VALUES(29,'rup','','Aromanian; Arumanian; Macedo-Romanian','');
INSERT INTO _lang VALUES(30,'art','','Artificial (Other)','');
INSERT INTO _lang VALUES(31,'asm','as','Assamese','');
INSERT INTO _lang VALUES(32,'ast','','Asturian; Bable','');
INSERT INTO _lang VALUES(33,'ath','','Athapascan languages','');
INSERT INTO _lang VALUES(34,'aus','','Australian languages','');
INSERT INTO _lang VALUES(35,'bar','','Austro-Bavarian','');
INSERT INTO _lang VALUES(36,'map','','Austronesian (Other)','');
INSERT INTO _lang VALUES(37,'ava','av','Avaric','');
INSERT INTO _lang VALUES(38,'ave','ae','Avestan','');
INSERT INTO _lang VALUES(39,'awa','','Awadhi','');
INSERT INTO _lang VALUES(40,'aym','ay','Aymara','');
INSERT INTO _lang VALUES(41,'aze','az','Azerbaijani','');
INSERT INTO _lang VALUES(42,'ban','','Balinese','');
INSERT INTO _lang VALUES(43,'bat','','Baltic (Other)','');
INSERT INTO _lang VALUES(44,'bal','','Baluchi','');
INSERT INTO _lang VALUES(45,'bam','bm','Bambara','');
INSERT INTO _lang VALUES(46,'bai','','Bamileke languages','');
INSERT INTO _lang VALUES(47,'bad','','Banda','');
INSERT INTO _lang VALUES(48,'bnt','','Bantu (Other)','');
INSERT INTO _lang VALUES(49,'bas','','Basa','');
INSERT INTO _lang VALUES(50,'bak','ba','Bashkir','');
INSERT INTO _lang VALUES(51,'eus','eu','Basque','');
INSERT INTO _lang VALUES(52,'baq','eu','Basque','');
INSERT INTO _lang VALUES(53,'btk','','Batak (Indonesia)','');
INSERT INTO _lang VALUES(54,'bej','','Beja','');
INSERT INTO _lang VALUES(55,'bel','be','Belarusian','');
INSERT INTO _lang VALUES(56,'bem','','Bemba','');
INSERT INTO _lang VALUES(57,'ben','bn','Bengali','');
INSERT INTO _lang VALUES(58,'ber','','Berber (Other)','');
INSERT INTO _lang VALUES(59,'bho','','Bhojpuri','');
INSERT INTO _lang VALUES(60,'bih','bh','Bihari','');
INSERT INTO _lang VALUES(61,'bik','','Bikol languages','');
INSERT INTO _lang VALUES(62,'bin','','Bini','');
INSERT INTO _lang VALUES(63,'bis','bi','Bislama','');
INSERT INTO _lang VALUES(64,'byn','','Blin; Bilin','');
INSERT INTO _lang VALUES(65,'bos','bs','Bosnian','');
INSERT INTO _lang VALUES(66,'bra','','Brij Bhasha','');
INSERT INTO _lang VALUES(67,'bre','br','Breton','');
INSERT INTO _lang VALUES(68,'bug','','Buginese','');
INSERT INTO _lang VALUES(69,'bul','bg','Bulgarian','');
INSERT INTO _lang VALUES(70,'bua','','Buriat','');
INSERT INTO _lang VALUES(71,'mya','my','Burmese','');
INSERT INTO _lang VALUES(72,'bur','my','Burmese','');
INSERT INTO _lang VALUES(73,'cad','','Caddo','');
INSERT INTO _lang VALUES(74,'car','','Carib','');
INSERT INTO _lang VALUES(75,'cat','ca','Catalan; Valencian','');
INSERT INTO _lang VALUES(76,'cau','','Caucasian (Other)','');
INSERT INTO _lang VALUES(77,'ceb','','Cebuano','');
INSERT INTO _lang VALUES(78,'cel','','Celtic (Other)','');
INSERT INTO _lang VALUES(79,'cai','','Central American Indian (Other)','');
INSERT INTO _lang VALUES(80,'chg','','Chagatai','');
INSERT INTO _lang VALUES(81,'cmc','','Chamic languages','');
INSERT INTO _lang VALUES(82,'cha','ch','Chamorro','');
INSERT INTO _lang VALUES(83,'che','ce','Chechen','');
INSERT INTO _lang VALUES(84,'chr','','Cherokee','');
INSERT INTO _lang VALUES(85,'chy','','Cheyenne','');
INSERT INTO _lang VALUES(86,'chb','','Chibcha','');
INSERT INTO _lang VALUES(87,'nya','ny','Chichewa; Chewa; Nyanja','');
INSERT INTO _lang VALUES(88,'zho','zh','Chinese','');
INSERT INTO _lang VALUES(89,'chi','zh','Chinese','');
INSERT INTO _lang VALUES(90,'chn','','Chinook jargon','');
INSERT INTO _lang VALUES(91,'cho','','Choctaw','');
INSERT INTO _lang VALUES(92,'chu','cu','Church Slavonic; Church Slavic; Old Church Slavoni','');
INSERT INTO _lang VALUES(93,'chk','','Chuukese','');
INSERT INTO _lang VALUES(94,'chv','cv','Chuvash','');
INSERT INTO _lang VALUES(95,'nwc','','Classical Newari; Old Newari; Classical Nepal Bhas','');
INSERT INTO _lang VALUES(96,'syc','','Classical Syriac','');
INSERT INTO _lang VALUES(97,'cop','','Coptic','');
INSERT INTO _lang VALUES(98,'cor','kw','Cornish','');
INSERT INTO _lang VALUES(99,'cos','co','Corsican','');
INSERT INTO _lang VALUES(100,'cre','cr','Cree','');
INSERT INTO _lang VALUES(101,'mus','','Creek; Muskogean','');
INSERT INTO _lang VALUES(102,'crp','','Creoles and Pidgins (Other)','');
INSERT INTO _lang VALUES(103,'cpe','','Creoles and Pidgins; English-based (Other)','');
INSERT INTO _lang VALUES(104,'cpf','','Creoles and Pidgins; French-based (Other)','');
INSERT INTO _lang VALUES(105,'cpp','','Creoles and Pidgins; Portuguese-based (Other)','');
INSERT INTO _lang VALUES(106,'crh','','Crimean Tatar (Crimean Turkish)','');
INSERT INTO _lang VALUES(107,'hrv','hr','Croatian','');
INSERT INTO _lang VALUES(108,'scr','hr','Croatian','');
INSERT INTO _lang VALUES(109,'cus','','Cushitic (Other)','');
INSERT INTO _lang VALUES(110,'ces','cs','Czech','');
INSERT INTO _lang VALUES(111,'cze','cs','Czech','');
INSERT INTO _lang VALUES(112,'dak','','Dakota','');
INSERT INTO _lang VALUES(113,'dan','da','Danish','');
INSERT INTO _lang VALUES(114,'dar','','Dargwa','');
INSERT INTO _lang VALUES(115,'day','','Dayak','');
INSERT INTO _lang VALUES(116,'del','','Delaware','');
INSERT INTO _lang VALUES(117,'chp','','Dene Suline','');
INSERT INTO _lang VALUES(118,'din','','Dinka','');
INSERT INTO _lang VALUES(119,'div','dv','Divehi; Dhivehi; Maldivian','');
INSERT INTO _lang VALUES(120,'doi','','Dogri','');
INSERT INTO _lang VALUES(121,'dgr','','Dogrib','');
INSERT INTO _lang VALUES(122,'dra','','Dravidian (Other)','');
INSERT INTO _lang VALUES(123,'dua','','Duala','');
INSERT INTO _lang VALUES(124,'nld','nl','Dutch; Flemish','');
INSERT INTO _lang VALUES(125,'dyu','nl','Dutch; Flemish','');
INSERT INTO _lang VALUES(126,'dum','','Dutch - Middle (ca. 1050-1350)','');
INSERT INTO _lang VALUES(127,'dyu','','Dyula','');
INSERT INTO _lang VALUES(128,'dzo','dz','Dzongkha','');
INSERT INTO _lang VALUES(129,'efi','','Efik','');
INSERT INTO _lang VALUES(130,'egy','','Egyptian (Ancient)','');
INSERT INTO _lang VALUES(131,'eka','','Ekajuk','');
INSERT INTO _lang VALUES(132,'elx','','Elamite','');
INSERT INTO _lang VALUES(133,'eng','en','English','');
INSERT INTO _lang VALUES(134,'enm','','English - Middle (ca. 1100-1500)','');
INSERT INTO _lang VALUES(135,'ang','','English - Old (ca. 450-1100)','');
INSERT INTO _lang VALUES(136,'myv','','Erzya','');
INSERT INTO _lang VALUES(137,'epo','eo','Esperanto','');
INSERT INTO _lang VALUES(138,'est','et','Estonian','');
INSERT INTO _lang VALUES(139,'ewe','ee','Ewe','');
INSERT INTO _lang VALUES(140,'ewo','','Ewondo','');
INSERT INTO _lang VALUES(141,'fan','','Fang','');
INSERT INTO _lang VALUES(142,'fat','','Fanti','');
INSERT INTO _lang VALUES(143,'fao','fo','Faroese','');
INSERT INTO _lang VALUES(144,'fij','fj','Fijian','');
INSERT INTO _lang VALUES(145,'fil','','Filipino','');
INSERT INTO _lang VALUES(146,'fin','fi','Finnish','');
INSERT INTO _lang VALUES(147,'fiu','','Finno-Ugrian (Other)','');
INSERT INTO _lang VALUES(148,'fon','','Fon','');
INSERT INTO _lang VALUES(149,'fra','fr','French','');
INSERT INTO _lang VALUES(150,'fre','fr','French','');
INSERT INTO _lang VALUES(151,'frm','','French - Middle (ca. 1400-1600)','');
INSERT INTO _lang VALUES(152,'fro','','French - Old (842-ca. 1400)','');
INSERT INTO _lang VALUES(153,'frs','','Frisian - Eastern','');
INSERT INTO _lang VALUES(154,'frr','','Frisian - Northern','');
INSERT INTO _lang VALUES(155,'fry','fy','Frisian - Western','');
INSERT INTO _lang VALUES(156,'fur','','Friulian','');
INSERT INTO _lang VALUES(157,'ful','ff','Fulah','');
INSERT INTO _lang VALUES(158,'gaa','','Ga','');
INSERT INTO _lang VALUES(159,'glg','gl','Galician','');
INSERT INTO _lang VALUES(160,'lug','lg','Ganda','');
INSERT INTO _lang VALUES(161,'gay','','Gayo','');
INSERT INTO _lang VALUES(162,'gba','','Gbaya','');
INSERT INTO _lang VALUES(163,'gez','','Ge''ez','');
INSERT INTO _lang VALUES(164,'kat','ka','Georgian','');
INSERT INTO _lang VALUES(165,'geo','ka','Georgian','');
INSERT INTO _lang VALUES(166,'deu','de','German','');
INSERT INTO _lang VALUES(167,'ger','de','German','');
INSERT INTO _lang VALUES(168,'gsw','','German - Alemannic','');
INSERT INTO _lang VALUES(169,'nds','','German - Low; Low German; Saxon; Low; Low Saxon','');
INSERT INTO _lang VALUES(170,'gmh','','German - Middle High (ca. 1050-1500)','');
INSERT INTO _lang VALUES(171,'goh','','German - Old High (ca. 750-1050)','');
INSERT INTO _lang VALUES(172,'gem','','Germanic (Other)','');
INSERT INTO _lang VALUES(173,'gil','','Gilbertese; Kiribati','');
INSERT INTO _lang VALUES(174,'gon','','Gondi','');
INSERT INTO _lang VALUES(175,'gor','','Gorontalo','');
INSERT INTO _lang VALUES(176,'got','','Gothic','');
INSERT INTO _lang VALUES(177,'grb','','Grebo','');
INSERT INTO _lang VALUES(178,'grc','','Greek - Ancient (to 1453)','');
INSERT INTO _lang VALUES(179,'ell','el','Greek - Modern (1453-)','');
INSERT INTO _lang VALUES(180,'gre','el','Greek - Modern (1453-)','');
INSERT INTO _lang VALUES(181,'kal','kl','Greenlandic; Kalaallisut','');
INSERT INTO _lang VALUES(182,'grn','gn','Guarani','');
INSERT INTO _lang VALUES(183,'guj','gu','Gujarati','');
INSERT INTO _lang VALUES(184,'gwi','','Gwich?in','');
INSERT INTO _lang VALUES(185,'hai','','Haida','');
INSERT INTO _lang VALUES(186,'hat','ht','Haitian Creole; Haitian','');
INSERT INTO _lang VALUES(187,'hau','ha','Hausa','');
INSERT INTO _lang VALUES(188,'haw','','Hawaiian','');
INSERT INTO _lang VALUES(189,'heb','he','Hebrew','');
INSERT INTO _lang VALUES(190,'her','hz','Herero','');
INSERT INTO _lang VALUES(191,'hil','','Hiligaynon','');
INSERT INTO _lang VALUES(192,'him','','Himachali','');
INSERT INTO _lang VALUES(193,'hin','hi','Hindi','');
INSERT INTO _lang VALUES(194,'hmo','ho','Hiri Motu','');
INSERT INTO _lang VALUES(195,'hit','','Hittite','');
INSERT INTO _lang VALUES(196,'hmn','','Hmong','');
INSERT INTO _lang VALUES(197,'hun','hu','Hungarian','');
INSERT INTO _lang VALUES(198,'hup','','Hupa','');
INSERT INTO _lang VALUES(199,'iba','','Iban','');
INSERT INTO _lang VALUES(200,'ice','is','Icelandic','');
INSERT INTO _lang VALUES(201,'isl','is','Icelandic','');
INSERT INTO _lang VALUES(202,'ido','io','Ido','');
INSERT INTO _lang VALUES(203,'ibo','ig','Igbo','');
INSERT INTO _lang VALUES(204,'ijo','','Ijo','');
INSERT INTO _lang VALUES(205,'ilo','','Iloko','');
INSERT INTO _lang VALUES(206,'smn','','Inari Sami','');
INSERT INTO _lang VALUES(207,'inc','','Indic (Other)','');
INSERT INTO _lang VALUES(208,'ine','','Indo-European (Other)','');
INSERT INTO _lang VALUES(209,'ind','id','Indonesian','');
INSERT INTO _lang VALUES(210,'inh','','Ingush','');
INSERT INTO _lang VALUES(211,'ina','ia','Interlingua (International Auxiliary Language Asso','');
INSERT INTO _lang VALUES(212,'ile','ie','Interlingue','');
INSERT INTO _lang VALUES(213,'iku','iu','Inuktitut','');
INSERT INTO _lang VALUES(214,'ipk','ik','Inupiaq','');
INSERT INTO _lang VALUES(215,'ira','','Iranian (Other)','');
INSERT INTO _lang VALUES(216,'gle','ga','Irish','');
INSERT INTO _lang VALUES(217,'mga','','Irish - Middle (900-1200)','');
INSERT INTO _lang VALUES(218,'sga','','Irish - Old (to 900)','');
INSERT INTO _lang VALUES(219,'iro','','Iroquoian languages','');
INSERT INTO _lang VALUES(220,'ita','it','Italian','');
INSERT INTO _lang VALUES(221,'jpn','ja','Japanese','');
INSERT INTO _lang VALUES(222,'jav','jv','Javanese','');
INSERT INTO _lang VALUES(223,'jrb','','Judeo-Arabic','');
INSERT INTO _lang VALUES(224,'jpr','','Judeo-Persian','');
INSERT INTO _lang VALUES(225,'kbd','','Kabardian','');
INSERT INTO _lang VALUES(226,'kab','','Kabyle','');
INSERT INTO _lang VALUES(227,'kac','','Kachin','');
INSERT INTO _lang VALUES(228,'xal','','Kalmyk; Oirat','');
INSERT INTO _lang VALUES(229,'kam','','Kamba','');
INSERT INTO _lang VALUES(230,'kan','kn','Kannada','');
INSERT INTO _lang VALUES(231,'kau','kr','Kanuri','');
INSERT INTO _lang VALUES(232,'krc','','Karachay-Balkar','');
INSERT INTO _lang VALUES(233,'kaa','','Kara-Kalpak','');
INSERT INTO _lang VALUES(234,'krl','','Karelian','');
INSERT INTO _lang VALUES(235,'kar','','Karen','');
INSERT INTO _lang VALUES(236,'kas','ks','Kashmiri','');
INSERT INTO _lang VALUES(237,'csb','','Kashubian','');
INSERT INTO _lang VALUES(238,'kaw','','Kawi','');
INSERT INTO _lang VALUES(239,'kaz','kk','Kazakh','');
INSERT INTO _lang VALUES(240,'kha','','Khasi','');
INSERT INTO _lang VALUES(241,'khm','km','Khmer','');
INSERT INTO _lang VALUES(242,'khi','','Khoisan (Other)','');
INSERT INTO _lang VALUES(243,'kho','','Khotanese','');
INSERT INTO _lang VALUES(244,'kik','ki','Kikuyu','');
INSERT INTO _lang VALUES(245,'kmb','','Kimbundu','');
INSERT INTO _lang VALUES(246,'kin','rw','Kinyarwanda','');
INSERT INTO _lang VALUES(247,'kir','ky','Kirghiz','');
INSERT INTO _lang VALUES(248,'tlh','','Klingon','');
INSERT INTO _lang VALUES(249,'kom','kv','Komi','');
INSERT INTO _lang VALUES(250,'kon','kg','Kongo','');
INSERT INTO _lang VALUES(251,'kok','','Konkani','');
INSERT INTO _lang VALUES(252,'kor','ko','Korean','');
INSERT INTO _lang VALUES(253,'kos','','Kosraean','');
INSERT INTO _lang VALUES(254,'kpe','','Kpelle','');
INSERT INTO _lang VALUES(255,'kro','','Kru','');
INSERT INTO _lang VALUES(256,'kua','kj','Kuanyama; Kwanyama','');
INSERT INTO _lang VALUES(257,'kum','','Kumyk','');
INSERT INTO _lang VALUES(258,'kur','ku','Kurdish','');
INSERT INTO _lang VALUES(259,'kru','','Kurukh','');
INSERT INTO _lang VALUES(260,'kut','','Kutenai','');
INSERT INTO _lang VALUES(261,'lad','','Ladino','');
INSERT INTO _lang VALUES(262,'lah','','Lahnda','');
INSERT INTO _lang VALUES(263,'lam','','Lamba','');
INSERT INTO _lang VALUES(264,'lao','lo','Lao','');
INSERT INTO _lang VALUES(265,'lat','la','Latin','');
INSERT INTO _lang VALUES(266,'lav','lv','Latvian','');
INSERT INTO _lang VALUES(267,'lez','','Lezghian','');
INSERT INTO _lang VALUES(268,'lim','li','Limburgish; Limburger; Limburgan','');
INSERT INTO _lang VALUES(269,'lin','ln','Lingala','');
INSERT INTO _lang VALUES(270,'lit','lt','Lithuanian','');
INSERT INTO _lang VALUES(271,'jbo','','Lojban','');
INSERT INTO _lang VALUES(272,'loz','','Lozi','');
INSERT INTO _lang VALUES(273,'lub','lu','Luba-Katanga','');
INSERT INTO _lang VALUES(274,'lua','','Luba-Lulua','');
INSERT INTO _lang VALUES(275,'lui','','LuiseÅ¯','');
INSERT INTO _lang VALUES(276,'smj','','Lule Sami','');
INSERT INTO _lang VALUES(277,'lun','','Lunda','');
INSERT INTO _lang VALUES(278,'luo','','Luo (Kenya and Tanzania)','');
INSERT INTO _lang VALUES(279,'lus','','Lushai','');
INSERT INTO _lang VALUES(280,'ltz','lb','Luxembourgish; Letzeburgesch','');
INSERT INTO _lang VALUES(281,'mkd','mk','Macedonian','');
INSERT INTO _lang VALUES(282,'mac','mk','Macedonian','');
INSERT INTO _lang VALUES(283,'mad','','Madurese','');
INSERT INTO _lang VALUES(284,'mag','','Magahi','');
INSERT INTO _lang VALUES(285,'mai','','Maithili','');
INSERT INTO _lang VALUES(286,'mak','','Makasar','');
INSERT INTO _lang VALUES(287,'mlg','mg','Malagasy','');
INSERT INTO _lang VALUES(288,'msa','ms','Malay','');
INSERT INTO _lang VALUES(289,'may','ms','Malay','');
INSERT INTO _lang VALUES(290,'mal','ml','Malayalam','');
INSERT INTO _lang VALUES(291,'mlt','mt','Maltese','');
INSERT INTO _lang VALUES(292,'mnc','','Manchu','');
INSERT INTO _lang VALUES(293,'mdr','','Mandar','');
INSERT INTO _lang VALUES(294,'man','','Mandingo','');
INSERT INTO _lang VALUES(295,'mni','','Manipuri','');
INSERT INTO _lang VALUES(296,'mno','','Manobo languages','');
INSERT INTO _lang VALUES(297,'glv','gv','Manx','');
INSERT INTO _lang VALUES(298,'mri','mi','M?ori','');
INSERT INTO _lang VALUES(299,'mao','mi','M?ori','');
INSERT INTO _lang VALUES(300,'mar','mr','Marathi','');
INSERT INTO _lang VALUES(301,'chm','','Mari','');
INSERT INTO _lang VALUES(302,'mah','mh','Marshallese','');
INSERT INTO _lang VALUES(303,'mwr','','Marwari','');
INSERT INTO _lang VALUES(304,'mas','','Masai','');
INSERT INTO _lang VALUES(305,'myn','','Mayan languages','');
INSERT INTO _lang VALUES(306,'men','','Mende','');
INSERT INTO _lang VALUES(307,'mic','','Mi''kmaq; Micmac','');
INSERT INTO _lang VALUES(308,'min','','Minangkabau','');
INSERT INTO _lang VALUES(309,'mwl','','Mirandese','');
INSERT INTO _lang VALUES(310,'moh','','Mohawk','');
INSERT INTO _lang VALUES(311,'mdf','','Moksha','');
INSERT INTO _lang VALUES(312,'mol','mo','Moldavian','');
INSERT INTO _lang VALUES(313,'mkh','','Mon-Khmer (Other)','');
INSERT INTO _lang VALUES(314,'lol','','Mongo','');
INSERT INTO _lang VALUES(315,'mon','mn','Mongolian','');
INSERT INTO _lang VALUES(316,'mos','','Mossi','');
INSERT INTO _lang VALUES(317,'mun','','Munda languages','');
INSERT INTO _lang VALUES(318,'nah','','Nahuatl','');
INSERT INTO _lang VALUES(319,'nau','na','Nauruan','');
INSERT INTO _lang VALUES(320,'nav','nv','Navajo; Navaho','');
INSERT INTO _lang VALUES(321,'nde','nd','Ndebele - North','');
INSERT INTO _lang VALUES(322,'nbl','nr','Ndebele- South','');
INSERT INTO _lang VALUES(323,'ndo','ng','Ndonga','');
INSERT INTO _lang VALUES(324,'nap','','Neapolitan','');
INSERT INTO _lang VALUES(325,'new','','Nepal Bhasa; Newari','');
INSERT INTO _lang VALUES(326,'nep','ne','Nepali','');
INSERT INTO _lang VALUES(327,'nia','','Nias','');
INSERT INTO _lang VALUES(328,'nic','','Niger-Kordofanian (Other)','');
INSERT INTO _lang VALUES(329,'ssa','','Nilo-Saharan (Other)','');
INSERT INTO _lang VALUES(330,'niu','','Niuean','');
INSERT INTO _lang VALUES(331,'nqo','','N''Ko','');
INSERT INTO _lang VALUES(332,'nog','','Nogai','');
INSERT INTO _lang VALUES(333,'non','','Norse (Old)','');
INSERT INTO _lang VALUES(334,'nai','','North American Indian (Other)','');
INSERT INTO _lang VALUES(335,'sme','se','Northern Sami','');
INSERT INTO _lang VALUES(336,'nor','no','Norwegian','');
INSERT INTO _lang VALUES(337,'nob','nb','Norwegian BokmÇ¬','');
INSERT INTO _lang VALUES(338,'nno','nn','Norwegian Nynorsk','');
INSERT INTO _lang VALUES(339,'nub','','Nubian languages','');
INSERT INTO _lang VALUES(340,'nym','','Nyamwezi','');
INSERT INTO _lang VALUES(341,'nyn','','Nyankole','');
INSERT INTO _lang VALUES(342,'nyo','','Nyoro','');
INSERT INTO _lang VALUES(343,'nzi','','Nzima','');
INSERT INTO _lang VALUES(344,'oci','oc','Occitan (post 1500); ProvenÈ¡l','');
INSERT INTO _lang VALUES(345,'oji','oj','Ojibwa (Anishinaabe languages)','');
INSERT INTO _lang VALUES(346,'ori','or','Oriya','');
INSERT INTO _lang VALUES(347,'orm','om','Oromo','');
INSERT INTO _lang VALUES(348,'osa','','Osage','');
INSERT INTO _lang VALUES(349,'oss','os','Ossetian; Ossetic','');
INSERT INTO _lang VALUES(350,'oto','','Otomian languages','');
INSERT INTO _lang VALUES(351,'pal','','Pahlavi (Middle Persian)','');
INSERT INTO _lang VALUES(352,'pau','','Palauan','');
INSERT INTO _lang VALUES(353,'pli','pi','Pali','');
INSERT INTO _lang VALUES(354,'pam','','Pampanga','');
INSERT INTO _lang VALUES(355,'pag','','Pangasinan','');
INSERT INTO _lang VALUES(356,'pap','','Papiamento','');
INSERT INTO _lang VALUES(357,'paa','','Papuan (Other)','');
INSERT INTO _lang VALUES(358,'fas','fa','Persian','');
INSERT INTO _lang VALUES(359,'per','fa','Persian','');
INSERT INTO _lang VALUES(360,'peo','','Persian - Old (ca. 600-400 BC)','');
INSERT INTO _lang VALUES(361,'phi','','Philippine (Other)','');
INSERT INTO _lang VALUES(362,'phn','','Phoenician','');
INSERT INTO _lang VALUES(363,'pon','','Pohnpeian','');
INSERT INTO _lang VALUES(364,'pol','pl','Polish','');
INSERT INTO _lang VALUES(365,'por','pt','Portuguese','');
INSERT INTO _lang VALUES(366,'pra','','Prakrit languages','');
INSERT INTO _lang VALUES(367,'pro','','ProvenÈ¡l - Old (to 1500)','');
INSERT INTO _lang VALUES(368,'pan','pa','Punjabi; Panjabi','');
INSERT INTO _lang VALUES(369,'pus','ps','Pushto','');
INSERT INTO _lang VALUES(370,'que','qu','Quechuan languages','');
INSERT INTO _lang VALUES(371,'roh','rm','Raeto-Romance','');
INSERT INTO _lang VALUES(372,'raj','','Rajasthani','');
INSERT INTO _lang VALUES(373,'rap','','Rapanui','');
INSERT INTO _lang VALUES(374,'rar','','Rarotongan','');
INSERT INTO _lang VALUES(375,'roa','','Romance (Other)','');
INSERT INTO _lang VALUES(376,'ron','ro','Romanian','');
INSERT INTO _lang VALUES(377,'rum','ro','Romanian','');
INSERT INTO _lang VALUES(378,'rom','','Romany','');
INSERT INTO _lang VALUES(379,'run','rn','Rundi','');
INSERT INTO _lang VALUES(380,'rus','ru','Russian','');
INSERT INTO _lang VALUES(381,'sal','','Salishan languages','');
INSERT INTO _lang VALUES(382,'sam','','Samaritan Aramaic','');
INSERT INTO _lang VALUES(383,'smi','','Sami languages (Other)','');
INSERT INTO _lang VALUES(384,'smo','sm','Samoan','');
INSERT INTO _lang VALUES(385,'sad','','Sandawe','');
INSERT INTO _lang VALUES(386,'sag','sg','Sango','');
INSERT INTO _lang VALUES(387,'san','sa','Sanskrit','');
INSERT INTO _lang VALUES(388,'sat','','Santali','');
INSERT INTO _lang VALUES(389,'srd','sc','Sardinian','');
INSERT INTO _lang VALUES(390,'sas','','Sasak','');
INSERT INTO _lang VALUES(391,'sco','','Scots','');
INSERT INTO _lang VALUES(392,'gla','gd','Scottish Gaelic; Gaelic','');
INSERT INTO _lang VALUES(393,'sel','','Selkup','');
INSERT INTO _lang VALUES(394,'sem','','Semitic (Other)','');
INSERT INTO _lang VALUES(395,'srp','sr','Serbo-Croatian','');
INSERT INTO _lang VALUES(396,'scc','sr','Serbo-Croatian','');
INSERT INTO _lang VALUES(397,'srr','','Serer','');
INSERT INTO _lang VALUES(398,'shn','','Shan','');
INSERT INTO _lang VALUES(399,'sna','sn','Shona','');
INSERT INTO _lang VALUES(400,'iii','ii','Sichuan Yi','');
INSERT INTO _lang VALUES(401,'scn','','Sicilian','');
INSERT INTO _lang VALUES(402,'sid','','Sidamo','');
INSERT INTO _lang VALUES(403,'sgn','','Sign languages','');
INSERT INTO _lang VALUES(404,'bla','','Siksika','');
INSERT INTO _lang VALUES(405,'snd','sd','Sindhi','');
INSERT INTO _lang VALUES(406,'sin','si','Sinhalese; Sinhala','');
INSERT INTO _lang VALUES(407,'sit','','Sino-Tibetan (Other)','');
INSERT INTO _lang VALUES(408,'sio','','Siouan languages','');
INSERT INTO _lang VALUES(409,'sms','','Skolt Sami','');
INSERT INTO _lang VALUES(410,'den','','Slave (Athapascan)','');
INSERT INTO _lang VALUES(411,'sla','','Slavic (Other)','');
INSERT INTO _lang VALUES(412,'slo','sk','Slovak','');
INSERT INTO _lang VALUES(413,'slk','sk','Slovak','');
INSERT INTO _lang VALUES(414,'slv','sl','Slovenian','');
INSERT INTO _lang VALUES(415,'sog','','Sogdian','');
INSERT INTO _lang VALUES(416,'som','so','Somali','');
INSERT INTO _lang VALUES(417,'son','','Songhai','');
INSERT INTO _lang VALUES(418,'snk','','Soninke','');
INSERT INTO _lang VALUES(419,'wen','','Sorbian languages','');
INSERT INTO _lang VALUES(420,'dsb','','Sorbian (Lower)','');
INSERT INTO _lang VALUES(421,'hsb','','Sorbian (Upper)','');
INSERT INTO _lang VALUES(422,'nso','','Sotho - Northern; Pedi; Sepedi','');
INSERT INTO _lang VALUES(423,'sot','st','Sotho - Southern','');
INSERT INTO _lang VALUES(424,'sai','','South American Indian (Other)','');
INSERT INTO _lang VALUES(425,'alt','','Southern Altai','');
INSERT INTO _lang VALUES(426,'sma','','Southern Sami','');
INSERT INTO _lang VALUES(427,'spa','es','Spanish; Castilian','');
INSERT INTO _lang VALUES(428,'srn','','Sranan Tongo','');
INSERT INTO _lang VALUES(429,'suk','','Sukuma','');
INSERT INTO _lang VALUES(430,'sux','','Sumerian','');
INSERT INTO _lang VALUES(431,'sun','su','Sundanese','');
INSERT INTO _lang VALUES(432,'sus','','Susu','');
INSERT INTO _lang VALUES(433,'swa','sw','Swahili','');
INSERT INTO _lang VALUES(434,'ssw','ss','Swati','');
INSERT INTO _lang VALUES(435,'swe','sv','Swedish','');
INSERT INTO _lang VALUES(436,'syr','','Syriac','');
INSERT INTO _lang VALUES(437,'tgl','tl','Tagalog','');
INSERT INTO _lang VALUES(438,'tah','ty','Tahitian','');
INSERT INTO _lang VALUES(439,'tai','','Tai (Other)','');
INSERT INTO _lang VALUES(440,'tgk','tg','Tajik','');
INSERT INTO _lang VALUES(441,'tmh','','Tamashek','');
INSERT INTO _lang VALUES(442,'tam','ta','Tamil','');
INSERT INTO _lang VALUES(443,'tat','tt','Tatar','');
INSERT INTO _lang VALUES(444,'tel','te','Telugu','');
INSERT INTO _lang VALUES(445,'ter','','Tereno','');
INSERT INTO _lang VALUES(446,'tet','','Tetum (Lia-Tetun)','');
INSERT INTO _lang VALUES(447,'tha','th','Thai','');
INSERT INTO _lang VALUES(448,'bod','bo','Tibetan','');
INSERT INTO _lang VALUES(449,'tib','bo','Tibetan','');
INSERT INTO _lang VALUES(450,'tig','','Tigre','');
INSERT INTO _lang VALUES(451,'tir','ti','Tigrinya','');
INSERT INTO _lang VALUES(452,'tem','','Timne','');
INSERT INTO _lang VALUES(453,'tiv','','Tiv','');
INSERT INTO _lang VALUES(454,'tli','','Tlingit','');
INSERT INTO _lang VALUES(455,'tpi','','Tok Pisin','');
INSERT INTO _lang VALUES(456,'tkl','','Tokelau','');
INSERT INTO _lang VALUES(457,'tog','','Tonga (Malawi)','');
INSERT INTO _lang VALUES(458,'ton','to','Tongan','');
INSERT INTO _lang VALUES(459,'tsi','','Tsimshian','');
INSERT INTO _lang VALUES(460,'tso','ts','Tsonga','');
INSERT INTO _lang VALUES(461,'tsn','tn','Tswana','');
INSERT INTO _lang VALUES(462,'tum','','Tumbuka','');
INSERT INTO _lang VALUES(463,'tup','','Tupi languages','');
INSERT INTO _lang VALUES(464,'tur','tr','Turkish','');
INSERT INTO _lang VALUES(465,'ota','','Turkish - Ottoman (1500-1928)','');
INSERT INTO _lang VALUES(466,'tuk','tk','Turkmen','');
INSERT INTO _lang VALUES(467,'tvl','','Tuvalu','');
INSERT INTO _lang VALUES(468,'tyv','','Tuvinian','');
INSERT INTO _lang VALUES(469,'twi','tw','Twi','');
INSERT INTO _lang VALUES(470,'udm','','Udmurt','');
INSERT INTO _lang VALUES(471,'uga','','Ugaritic','');
INSERT INTO _lang VALUES(472,'uig','ug','Uighur; Uyghur','');
INSERT INTO _lang VALUES(473,'ukr','uk','Ukrainian','');
INSERT INTO _lang VALUES(474,'umb','','Umbundu','');
INSERT INTO _lang VALUES(475,'urd','ur','Urdu','');
INSERT INTO _lang VALUES(476,'uzb','uz','Uzbek','');
INSERT INTO _lang VALUES(477,'vai','','Vai','');
INSERT INTO _lang VALUES(478,'ven','ve','Venda','');
INSERT INTO _lang VALUES(479,'vie','vi','Vietnamese','');
INSERT INTO _lang VALUES(480,'vol','vo','VolapÂ«','');
INSERT INTO _lang VALUES(481,'vot','','Votic','');
INSERT INTO _lang VALUES(482,'wak','','Wakashan languages','');
INSERT INTO _lang VALUES(483,'wal','','Walamo','');
INSERT INTO _lang VALUES(484,'wln','wa','Walloon','');
INSERT INTO _lang VALUES(485,'war','','Waray','');
INSERT INTO _lang VALUES(486,'was','','Washo','');
INSERT INTO _lang VALUES(487,'wel','cy','Welsh','');
INSERT INTO _lang VALUES(488,'cym','cy','Welsh','');
INSERT INTO _lang VALUES(489,'wol','wo','Wolof','');
INSERT INTO _lang VALUES(490,'xho','xh','Xhosa','');
INSERT INTO _lang VALUES(491,'sah','','Yakut','');
INSERT INTO _lang VALUES(492,'yao','','Yao','');
INSERT INTO _lang VALUES(493,'yap','','Yapese','');
INSERT INTO _lang VALUES(494,'yid','yi','Yiddish','');
INSERT INTO _lang VALUES(495,'yor','yo','Yoruba','');
INSERT INTO _lang VALUES(496,'ypk','','Yupik languages','');
INSERT INTO _lang VALUES(497,'znd','','Zande','');
INSERT INTO _lang VALUES(498,'zza','','Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki','');
INSERT INTO _lang VALUES(499,'zap','','Zapotec','');
INSERT INTO _lang VALUES(500,'zen','','Zenaga','');
INSERT INTO _lang VALUES(501,'zha','za','Zhuang; Chuang','');
INSERT INTO _lang VALUES(502,'zul','zu','Zulu','');
INSERT INTO _lang VALUES(503,'zun','','Zuni','');
INSERT INTO _lang VALUES(504,'eng','en_gb','English (GB)','');
CREATE TABLE _status (ID INTEGER PRIMARY KEY, status TEXT);
INSERT INTO _status VALUES(1,'Married');
INSERT INTO _status VALUES(3,'Single');
INSERT INTO _status VALUES(4,'Seperated');
INSERT INTO _status VALUES(5,'Divorced');
INSERT INTO _status VALUES(6,'Civil Partnership');
INSERT INTO _status VALUES(7,'Common-law marriage');
INSERT INTO _status VALUES(8,'Widowed');
CREATE TABLE _titles (ID INTEGER PRIMARY KEY, title TEXT);
INSERT INTO _titles VALUES(1,'Mr');
INSERT INTO _titles VALUES(2,'Mrs');
INSERT INTO _titles VALUES(3,'Miss');
INSERT INTO _titles VALUES(4,'Ms');
INSERT INTO _titles VALUES(5,'Dr');
INSERT INTO _titles VALUES(6,'Rev');
INSERT INTO _titles VALUES(7,'Sir');
INSERT INTO _titles VALUES(8,'Lord');
CREATE TABLE content (ID INTEGER PRIMARY KEY, entityID NUMERIC, heading TEXT, HTMLTitle TEXT, extraHead TEXT, description TEXT, keywords TEXT, HTML TEXT, topFeature TEXT, rightFeature TEXT, leftFeature TEXT, lang TEXT, media TEXT, CDate , UDate , updatedBy TEXT, current TEXT);
INSERT INTO content VALUES(1,1,'Impact CRM &amp; CMS','Impact CRM &amp; CMS','','Impact is an Open Source Project, which aims to build a combined Content & Relationship Management Platform','CRM,CMS,Church,Database','<p>Impact is an Open Source Project, which aims to build a combined Content &amp; Relationship Management Platform.  The Primary auidance is Churches, Charities and Community groups.  The flexibility of the platform should make it suitable for small business'' as well.  The platform will allow plugins and have an adanced templating system.</p>	<h2>Project Links</h2>	<ul>		<li><a href=\http://sourceforge.net/p/impactcrm/home/\>Project page</a></li>		<li><a href=\http://impact-crm.com\>Development Blog</a></li>	</ul>','','','','en_gb','PC','0000-00-00 00:00:00','0000-00-00 00:00:00','Stephen Simpson','YES');
CREATE TABLE entities (ID INTEGER PRIMARY KEY, title TEXT, readers TEXT, editors TEXT, managers TEXT, application TEXT);
INSERT INTO entities VALUES(1,'home','[WEB],[ADMIN]','[ADMIN]','[ADMIN]','Normal');
CREATE TABLE person (ID INTEGER PRIMARY KEY, title NUMERIC, firstname TEXT, middlenames TEXT, surname TEXT, maidenname TEXT, knownas TEXT, birthday TEXT, birthyear NUMERIC, gender TEXT, status NUMERIC);
CREATE TABLE structure (ID INTEGER PRIMARY KEY, entityID NUMERIC, DCType TEXT, title TEXT, menu TEXT, path TEXT, sequence TEXT, crawlerPriority NUMERIC, crawerFrequency TEXT, lang TEXT, include TEXT);
INSERT INTO structure VALUES(1,1,'Text','Home','MAIN','home','A',0.5,'monthly','en_gb','YES');
CREATE TABLE users (ID INTEGER PRIMARY KEY, personID NUMERIC, FBID NUMERIC, roles TEXT, access TEXT);
INSERT INTO users VALUES(1,0,0,'[WEB]',0);
CREATE INDEX entity_2_content ON content(entityID ASC);
CREATE INDEX entity_2_structure ON structure(entityID ASC);
COMMIT;
